### ISSUE TITLE
Engine Update Issue Tracker

### ISSUE THREAD

**Issue by sleepyyapril** [TheDenSS14/TheDen#55]
This is a list of bugs I've encountered since the update!

- [ ] Paradox anomaly objectives are broken.
- [ ] Opening your backpack and then pressing E on another backpack does not open the backpack, it breaks.
- [ ] Borgs take damge from glass shards on the floor if you walk over them.
- [ ] Borgs are affected by the traits selected in the character creator, resulting in me having functional platelet factories.
- [ ] A borg that is somehow laying down can put itself to sleep and thus hear telepathic comms.
- [ ] Borgs can get stuck in a crawling state after being revived while still moving at full speed, allowing them to ignore tables and railings when they move.
